title: Ishan Tarunesh
# position: Engineer
# affiliation: Samsung Electronics
email: ishantarunesh@gmail.com
keywords: minimal academic
avatar: ./assets/img/avatar.png

permalink: writings/:title
remote_theme: yaoyao-liu/minimal-light